services:
  api:
    build:
      context: ./
    env_file: .env
    command: uv run -- uvicorn chris.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips 172.16.0.0/12
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started

  web:
    build:
      context: ./chris-frontend
    depends_on:
      - api
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://api:8000
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    env_file: .env
    command:
      - start
      - --http-enabled=true
      - --proxy-headers=xforwarded
      - --proxy-trusted-addresses=172.16.0.0/12
    ports:
      - "8080:8080"
    volumes:
      - ./chris-keycloak/keycloak-discord-0.6.1.jar:/opt/keycloak/providers/keycloak-discord-0.6.1.jar
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    env_file: .env
    volumes:
      - ./chris-postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
