name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13" # Specify your desired Python version
          enable-cache: true # Optional: enables caching for faster installs

      - name: Install dependencies
        run: uv sync --dev

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run linting
        run: uv run ruff check .

      - name: Run Prettier checks
        run: cd chris-frontend && prettier -c ./

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest -q --tb=short || echo "No tests found"
